#!/bin/bash
set -euo pipefail

# CLAUDE_CODE_OAUTH_TOKEN is the env var the Claude CLI reads on every invocation
# for subscription-based auth (set via the ECS secrets block in ecs.tf).
# The value is a setup token generated by `claude setup-token` on a locally
# authenticated machine. No explicit login step is needed — the CLI uses it
# directly as a Bearer token.

# Inject Codex/OpenAI subscription credentials
if [[ -n "${CODEX_CREDENTIALS:-}" ]]; then
  mkdir -p /paperclip/.codex
  echo "$CODEX_CREDENTIALS" > /paperclip/.codex/credentials.json
  echo "[entrypoint] Codex credentials written to /paperclip/.codex/credentials.json"
fi

# Authenticate gh CLI using GitHub App (preferred) or PAT fallback
if [[ -n "${GITHUB_APP_ID:-}" && -n "${GITHUB_APP_PRIVATE_KEY:-}" && -n "${GITHUB_APP_INSTALLATION_ID:-}" ]]; then
  echo "[entrypoint] Authenticating gh CLI via GitHub App..."

  # GITHUB_APP_PRIVATE_KEY is the raw PEM private key.
  # ECS Secrets Manager may inject it with literal \n instead of actual newlines —
  # use printf '%b' to convert escape sequences to real characters.
  TMPKEY=$(mktemp)
  chmod 600 "$TMPKEY"
  printf '%b' "$GITHUB_APP_PRIVATE_KEY" > "$TMPKEY"

  # Validate the PEM key before attempting JWT generation
  if ! openssl rsa -in "$TMPKEY" -check -noout 2>/dev/null; then
    echo "[entrypoint] ERROR: GITHUB_APP_PRIVATE_KEY is invalid or malformed (openssl check failed)" >&2
    echo "[entrypoint] Key file line count: $(wc -l < "$TMPKEY"), size: $(wc -c < "$TMPKEY") bytes" >&2
    rm -f "$TMPKEY"
    exit 1
  fi

  # Generate a JWT signed with RS256 for the GitHub App using Node.js crypto.
  # The bash base64|openssl pipeline was fragile across environments (AHE-378).
  # node:crypto is built-in — no extra deps required.
  JWT=$(TMPKEY="$TMPKEY" GITHUB_APP_ID="$GITHUB_APP_ID" node -e '
    const crypto = require("crypto"), fs = require("fs");
    const key = fs.readFileSync(process.env.TMPKEY, "utf8");
    const now = Math.floor(Date.now() / 1000);
    const h = Buffer.from(JSON.stringify({alg:"RS256",typ:"JWT"})).toString("base64url");
    const p = Buffer.from(JSON.stringify({iat:now-60,exp:now+600,iss:process.env.GITHUB_APP_ID})).toString("base64url");
    const s = crypto.createSign("RSA-SHA256"); s.update(h+"."+p);
    process.stdout.write(h+"."+p+"."+s.sign(key,"base64url"));
  ')
  rm -f "$TMPKEY"

  # Exchange JWT for an installation access token — capture body on failure for debugging
  RESP=$(curl -s --fail-with-body -X POST \
    -H "Authorization: Bearer ${JWT}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/app/installations/${GITHUB_APP_INSTALLATION_ID}/access_tokens") || {
    echo "[entrypoint] ERROR: GitHub App token exchange failed. Response:" >&2
    echo "$RESP" >&2
    exit 1
  }

  GITHUB_INSTALLATION_TOKEN=$(node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).token)" <<< "$RESP")

  if [[ -z "${GITHUB_INSTALLATION_TOKEN:-}" ]]; then
    echo "[entrypoint] ERROR: Failed to obtain GitHub App installation token" >&2
    exit 1
  fi

  echo "$GITHUB_INSTALLATION_TOKEN" | gh auth login --with-token
  echo "[entrypoint] gh CLI authenticated via GitHub App (installation ${GITHUB_APP_INSTALLATION_ID})"

  # Installation tokens expire after 1 hour. Start a background loop that refreshes
  # the token every 50 minutes so long-running containers stay authenticated.
  (
    set +e
    while true; do
      sleep 3000
      echo "[entrypoint] Refreshing GitHub App installation token..."
      _TMPKEY=$(mktemp); chmod 600 "$_TMPKEY"
      printf '%b' "$GITHUB_APP_PRIVATE_KEY" > "$_TMPKEY"
      _JWT=$(TMPKEY="$_TMPKEY" GITHUB_APP_ID="$GITHUB_APP_ID" node -e '
        const crypto = require("crypto"), fs = require("fs");
        const key = fs.readFileSync(process.env.TMPKEY, "utf8");
        const now = Math.floor(Date.now() / 1000);
        const h = Buffer.from(JSON.stringify({alg:"RS256",typ:"JWT"})).toString("base64url");
        const p = Buffer.from(JSON.stringify({iat:now-60,exp:now+600,iss:process.env.GITHUB_APP_ID})).toString("base64url");
        const s = crypto.createSign("RSA-SHA256"); s.update(h+"."+p);
        process.stdout.write(h+"."+p+"."+s.sign(key,"base64url"));
      ') || { echo "[entrypoint] ERROR: JWT generation failed during token refresh" >&2; rm -f "$_TMPKEY"; continue; }
      rm -f "$_TMPKEY"
      _RESP=$(curl -s --fail-with-body -X POST \
        -H "Authorization: Bearer ${_JWT}" \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        "https://api.github.com/app/installations/${GITHUB_APP_INSTALLATION_ID}/access_tokens") || { echo "[entrypoint] ERROR: token exchange failed during refresh" >&2; continue; }
      _TOKEN=$(node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).token)" <<< "$_RESP") || { echo "[entrypoint] ERROR: token parse failed during refresh" >&2; continue; }
      if [[ -n "$_TOKEN" ]]; then
        echo "$_TOKEN" | gh auth login --with-token
        echo "[entrypoint] gh CLI token refreshed (installation ${GITHUB_APP_INSTALLATION_ID})"
      else
        echo "[entrypoint] ERROR: empty token during refresh" >&2
      fi
    done
  ) &
  echo "[entrypoint] Token refresh loop started (PID $!, interval 50m)"

elif [[ -n "${GITHUB_TOKEN:-}" ]]; then
  # gh CLI automatically picks up GITHUB_TOKEN from the environment — no explicit
  # login call needed (and gh auth login --with-token errors when the env var is set).
  echo "[entrypoint] gh CLI will use GITHUB_TOKEN from environment"
fi

# Write a .bashrc that preserves the full PATH for agent shell sessions.
# Claude CLI's Bash tool initialises from the user's shell profile, and
# Debian's /etc/profile resets PATH to a default that drops mise shims.
# This .bashrc re-exports the container's intended PATH so agents always
# have access to tools installed in the Dockerfile (yq, logcli, aws, etc.).
cat > /paperclip/.bashrc <<'BASHRC'
# Paperclip agent shell initialisation
export PATH="/paperclip/.local/share/mise/shims:/usr/local/bin:/usr/bin:/bin"
# Activate mise if available (provides erlang, elixir, ruby, python runtimes)
if command -v mise &>/dev/null; then
  eval "$(mise activate bash 2>/dev/null)" || true
fi
BASHRC

# Bootstrap the first admin invite if requested
# Set BOOTSTRAP_CEO_BASE_URL to your public URL (e.g. https://app.example.com)
# The invite URL will be printed to container logs (e.g. CloudWatch).
# Safe to leave set permanently — skips automatically once an admin exists.
if [[ -n "${BOOTSTRAP_CEO_BASE_URL:-}" ]]; then
  echo "[entrypoint] Running bootstrap-ceo (base-url=${BOOTSTRAP_CEO_BASE_URL})"
  node --import ./cli/node_modules/tsx/dist/loader.mjs cli/src/index.ts auth bootstrap-ceo \
    --base-url "${BOOTSTRAP_CEO_BASE_URL}" || true
fi


exec node --import ./server/node_modules/tsx/dist/loader.mjs server/dist/index.js
