#!/bin/bash
set -euo pipefail

# CLAUDE_CODE_OAUTH_TOKEN is the env var the Claude CLI reads on every invocation
# for subscription-based auth (set via the ECS secrets block in ecs.tf).
# The value is a setup token generated by `claude setup-token` on a locally
# authenticated machine. No explicit login step is needed — the CLI uses it
# directly as a Bearer token.

# Inject Codex/OpenAI subscription credentials
if [[ -n "${CODEX_CREDENTIALS:-}" ]]; then
  mkdir -p /paperclip/.codex
  echo "$CODEX_CREDENTIALS" > /paperclip/.codex/credentials.json
  echo "[entrypoint] Codex credentials written to /paperclip/.codex/credentials.json"
fi

# Authenticate gh CLI using GitHub App (preferred) or PAT fallback
if [[ -n "${GITHUB_APP_ID:-}" && -n "${PAPERCLIP_GITHUB_APP_PRIVATE_KEY:-}" && -n "${GITHUB_APP_INSTALLATION_ID:-}" ]]; then
  echo "[entrypoint] Authenticating gh CLI via GitHub App..."

  # PAPERCLIP_GITHUB_APP_PRIVATE_KEY must be base64-encoded PEM
  TMPKEY=$(mktemp)
  chmod 600 "$TMPKEY"
  echo "$PAPERCLIP_GITHUB_APP_PRIVATE_KEY" | base64 -d > "$TMPKEY"

  # Generate a JWT signed with RS256 for the GitHub App
  NOW=$(date +%s)
  IAT=$((NOW - 60))
  EXP=$((NOW + 600))

  b64url() { base64 -w 0 | tr '+/' '-_' | tr -d '='; }

  HEADER=$(printf '{"alg":"RS256","typ":"JWT"}' | b64url)
  PAYLOAD=$(printf '{"iat":%d,"exp":%d,"iss":"%s"}' "$IAT" "$EXP" "$GITHUB_APP_ID" | b64url)
  SIG=$(printf '%s.%s' "$HEADER" "$PAYLOAD" | openssl dgst -sha256 -sign "$TMPKEY" -binary | b64url)
  JWT="${HEADER}.${PAYLOAD}.${SIG}"
  rm -f "$TMPKEY"

  # Exchange JWT for an installation access token
  RESP=$(curl -sf -X POST \
    -H "Authorization: Bearer ${JWT}" \
    -H "Accept: application/vnd.github+json" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "https://api.github.com/app/installations/${GITHUB_APP_INSTALLATION_ID}/access_tokens")

  GITHUB_INSTALLATION_TOKEN=$(node -e "process.stdout.write(JSON.parse(require('fs').readFileSync('/dev/stdin','utf8')).token)" <<< "$RESP")

  if [[ -z "${GITHUB_INSTALLATION_TOKEN:-}" ]]; then
    echo "[entrypoint] ERROR: Failed to obtain GitHub App installation token" >&2
    exit 1
  fi

  echo "$GITHUB_INSTALLATION_TOKEN" | gh auth login --with-token
  echo "[entrypoint] gh CLI authenticated via GitHub App (installation ${GITHUB_APP_INSTALLATION_ID})"

elif [[ -n "${GITHUB_TOKEN:-}" ]]; then
  echo "$GITHUB_TOKEN" | gh auth login --with-token
  echo "[entrypoint] gh CLI authenticated via personal access token"
fi

# Write a .bashrc that preserves the full PATH for agent shell sessions.
# Claude CLI's Bash tool initialises from the user's shell profile, and
# Debian's /etc/profile resets PATH to a default that drops mise shims.
# This .bashrc re-exports the container's intended PATH so agents always
# have access to tools installed in the Dockerfile (yq, logcli, aws, etc.).
cat > /paperclip/.bashrc <<'BASHRC'
# Paperclip agent shell initialisation
export PATH="/paperclip/.local/share/mise/shims:/usr/local/bin:/usr/bin:/bin"
# Activate mise if available (provides erlang, elixir, ruby, python runtimes)
if command -v mise &>/dev/null; then
  eval "$(mise activate bash 2>/dev/null)" || true
fi
BASHRC

# Bootstrap the first admin invite if requested
# Set BOOTSTRAP_CEO_BASE_URL to your public URL (e.g. https://app.example.com)
# The invite URL will be printed to container logs (e.g. CloudWatch).
# Safe to leave set permanently — skips automatically once an admin exists.
if [[ -n "${BOOTSTRAP_CEO_BASE_URL:-}" ]]; then
  echo "[entrypoint] Running bootstrap-ceo (base-url=${BOOTSTRAP_CEO_BASE_URL})"
  node --import ./cli/node_modules/tsx/dist/loader.mjs cli/src/index.ts auth bootstrap-ceo \
    --base-url "${BOOTSTRAP_CEO_BASE_URL}" || true
fi


exec node --import ./server/node_modules/tsx/dist/loader.mjs server/dist/index.js
